search_beverage.settings:
  type: config_object
  label: 'Search beverage form settings'
  mapping:
    api_endpoint:
      type: string
      label: 'API endpoint URI'
    items_per_page:
      type: integer
      label: 'Number of items displayed on the search'
